# Generated by Django 3.2.16 on 2022-11-21 18:47

from django.db import migrations


def forwards_func(apps, schema_editor):

    CourseTeachers = apps.get_model("mainapp", "CourseTeachers")

    CourseTeachers.objects.create(
        id=8,
        name_first="Сергей",
        name_second="Лебедев",
        day_birth="1990-01-02",
    )

    CourseTeachers.objects.create(
        id=9,
        name_first="Елена",
        name_second="Каримова",
        day_birth="1988-10-05",
    )

    CourseTeachers.objects.create(
        id=10,
        name_first="Василий",
        name_second="Егоров",
        day_birth="1979-02-08",
    )


def reverse_func(apps, schema_editor):
    # Get model
    CourseTeachers = apps.get_model("mainapp", "CourseTeachers")
    # Delete objects
    CourseTeachers.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_lesson_migration"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
